import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {generate} from './generate.mjs';
if(!process.env.ART_DIR)throw Error('ART_DIR required');const art=path.resolve(process.env.ART_DIR),out=path.join(art,'unit-fixture');fs.mkdirSync(out,{recursive:true});const sha=b=>crypto.createHash('sha256').update(b).digest('hex');const file=(name,body)=>{const b=Buffer.from(body);fs.writeFileSync(path.join(out,name),b);return{file:name,bytes:b.length,sha256:sha(b)}};
const tex=file('shared.png','fixture texture');const zones=['garden','pond','temple','bazaar','outer','fangbang'].map(id=>{const raw=file(`${id}.glb`,`fixture raw ${id}`),cm=file(`${id}.cm.glb`,`fixture cm ${id}`);return{id,...raw,loadPolicy:id==='outer'?'deferred':id==='fangbang'?'on-demand':undefined,cm:{...cm,textures:['shared.png']}}});const manifest={schema:2,zones,textures:{'shared.png':{bytes:tex.bytes,sha256:tex.sha256}}};const mf=path.join(out,'zones-manifest.json');fs.writeFileSync(mf,JSON.stringify(manifest));const opts={id:'explicit-fixture',buildHead:'a'.repeat(40),packageHead:'b'.repeat(40),out,manifest:mf,fixture:true};
let n=0;const check=(name,f)=>{f();n++;console.log('PASS',name)};
check('missing review receipts stay unverified',()=>assert.equal(generate(opts).technicalStatus,'unverified'));
check('first-load unique texture counted once',()=>{const s=generate(opts);assert.equal(s.budget.uniqueTextureFiles,1);assert.equal(s.budget.uniqueTextureBytes,tex.bytes);assert.equal(s.budget.glbBytes,zones.filter(e=>!e.loadPolicy).reduce((n,e)=>n+e.cm.bytes,0))});
const old=path.join(art,'old-adopt.json');fs.writeFileSync(old,JSON.stringify({ownerAdopted:true,adoption:'adopt_all',status:'passed'}));check('historical adopt does not propagate',()=>{const s=generate({...opts,receipts:{technical:old}});assert.equal(s.adoption.status,'pending');assert.equal(s.archive.status,'pending');assert.equal(s.technicalStatus,'unverified')});
const proof=path.join(art,'proof.json');fs.writeFileSync(proof,JSON.stringify({fixture:true,pass:true}));const receipts={};for(const kind of['technical','walk','control','restore']){const f=path.join(art,kind+'-fixture-review.json');fs.writeFileSync(f,JSON.stringify({schemaVersion:1,kind,candidateId:opts.id,buildHead:opts.buildHead,manifestSha256:sha(fs.readFileSync(mf)),status:'passed',fixture:true,reusedFrom:'explicit-old-proof',reason:'explicit fixture geometry-preservation review',evidence:[{path:proof,sha256:sha(fs.readFileSync(proof))}]}));receipts[kind]=f}
check('bound four-category fixture reviews',()=>assert.equal(generate({...opts,receipts}).technicalStatus,'passed'));
check('fixture proofs cannot become final candidate',()=>assert.equal(generate({...opts,fixture:false,receipts}).technicalStatus,'unverified'));
check('old head receipt stays unverified',()=>assert.equal(generate({...opts,buildHead:'c'.repeat(40),receipts}).technicalStatus,'unverified'));
const bad=path.join(art,'bad-hash-review.json');const r=JSON.parse(fs.readFileSync(receipts.walk));r.evidence[0].sha256='0'.repeat(64);fs.writeFileSync(bad,JSON.stringify(r));check('bad evidence hash rejected',()=>assert.equal(generate({...opts,receipts:{...receipts,walk:bad}}).technicalStatus,'unverified'));
const noReason=path.join(art,'no-reuse-reason.json');r.evidence[0].sha256=sha(fs.readFileSync(proof));r.reason='';fs.writeFileSync(noReason,JSON.stringify(r));check('old PASS reuse requires explicit reason',()=>assert.equal(generate({...opts,receipts:{...receipts,walk:noReason}}).technicalStatus,'unverified'));
const missing=path.join(art,'missing-manifest.json');const incomplete={...manifest,zones:zones.filter(z=>z.id!=='fangbang')};fs.writeFileSync(missing,JSON.stringify(incomplete));check('incomplete v1 scope unverified',()=>assert.equal(generate({...opts,manifest:missing,receipts}).technicalStatus,'unverified'));
const before=fs.readFileSync(path.join(out,'garden.glb'));fs.writeFileSync(path.join(out,'garden.glb'),'corrupt');check('asset hash mismatch invalidates status',()=>assert.equal(generate({...opts,receipts}).technicalStatus,'unverified'));fs.writeFileSync(path.join(out,'garden.glb'),before);
check('explicit separate package HEAD preserved',()=>{const s=generate({...opts,receipts});assert.equal(s.sourceBuildHead,opts.buildHead);assert.equal(s.packageHead,opts.packageHead)});
fs.writeFileSync(path.join(art,'UNIT-CHECK.json'),JSON.stringify({time:new Date().toISOString(),passed:n,fixture:true,scope:'candidate generator only; no scene or walk simulation'},null,2)+'\n');
