// Real food socket + snack motion contract; no DOM, server or texture fixture.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import * as THREE from 'three';
import {loadFoodCatalog} from '../scene-authoring/yuyuan-area/web/play/foods.js';
import {PlayAvatar} from '../scene-authoring/yuyuan-area/web/play/avatar.js';
import {BikeView} from '../scene-authoring/yuyuan-area/web/play/bike-view.js';
const area=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../scene-authoring/yuyuan-area');
const manifest=JSON.parse(await fs.readFile(path.join(area,'inputs/play-foods.json'),'utf8'));
const originalFetch=globalThis.fetch;
globalThis.fetch=async input=>new Response(await fs.readFile(path.join(area,String(input).replace(/^\//,''))));
const catalog=await loadFoodCatalog({foods:[{id:'xiaolongbao'}],manifest});globalThis.fetch=originalFetch;
const model=new THREE.Group(),arm=new THREE.Bone();arm.name='armR';arm.position.set(-.19,.48,.12);model.add(arm);
const leg=new THREE.Bone();leg.name='legL';leg.position.set(.13,.2,-.04);model.add(leg);
model.add(new THREE.Mesh(new THREE.BoxGeometry(.32,.9,.2),new THREE.MeshBasicMaterial()));
const clips=['idle','walk','eat'].map(name=>new THREE.AnimationClip(name,2,[new THREE.QuaternionKeyframeTrack('armR.quaternion',[0,2],[0,0,0,1,0,0,0,1])]));
const avatar=new PlayAvatar({gltfScene:model,animations:clips});
avatar.setHoldingPose?.(true);avatar.update({feet:[0,0,0],yaw:0,moving:false,paused:false,dt:.02});
const holder=catalog.attachToHand('xiaolongbao',arm);
const grip=()=>{avatar.root.updateMatrixWorld(true);return holder.getObjectByName('socket_grip').getWorldPosition(new THREE.Vector3());};
const shoulder=()=>arm.getWorldPosition(new THREE.Vector3());
const localGrip=arm.worldToLocal(grip().clone());
let failures=0;const check=(name,ok,detail)=>{console.log(`${ok?'ok':'FAIL'} ${name} ${detail??''}`);if(!ok)failures++;};
check('real food grip is on the lower paw, beyond the shoulder joint',localGrip.y<-.08&&localGrip.length()>.11&&localGrip.length()<.21,localGrip.toArray());
const mouth=()=>avatar.root.localToWorld(new THREE.Vector3(0,.68,.28));
const before=grip().distanceTo(mouth());avatar.setEatingPose(true);
for(let i=0;i<36;i++)avatar.update({feet:[0,0,0],yaw:0,moving:false,paused:false,dt:1/60});
const after=grip().distanceTo(mouth());
check('eating raises the real grip toward the mouth',after<before*.78,`${before.toFixed(3)}m -> ${after.toFixed(3)}m`);
check('snack motion stays within the plush arm deformation budget',arm.quaternion.angleTo(avatar.restBoneQuaternions.get('armR'))<1.35);
const frozen=grip();avatar.update({feet:[0,0,0],yaw:0,moving:false,paused:true,dt:10});
check('paused snack pose stays frozen',grip().distanceTo(frozen)<1e-7);
avatar.setEatingPose(false);avatar.setHoldingPose?.(false);
leg.rotateX(.9); // A different last walk phase must not change the riding pose.
const bikeRoot=new THREE.Group(),seat=new THREE.Object3D();seat.position.y=.4;bikeRoot.add(seat);
const bike=new BikeView({root:bikeRoot,seat});bike.attachRider(avatar);bike.sit(avatar,0,0);
check('mounting uses the neutral limb basis rather than the last walking phase',leg.rotation.x<0&&leg.rotation.x>-.8,leg.rotation.x);
bike.detachRider(avatar);
const entry=catalog.byId.get('xiaolongbao'),display=catalog.makeDisplay('xiaolongbao');let disposed=0;
entry.proto.traverse(o=>{if(o.isMesh)o.geometry.addEventListener('dispose',()=>disposed++);});
const basket=new THREE.Group();basket.add(holder);
const returned=catalog.attachToHand('xiaolongbao',arm,holder);
check('basket to hand transfers the same food instance',returned===holder&&holder.parent===arm);
avatar.dispose();check('actor disposal leaves catalog-owned food geometry alive',disposed===0);
catalog.detach(returned);check('consumption detaches hand without disposing shared stall geometry',disposed===0&&display.children.length>0);
catalog.dispose();assert.equal(failures,0,'snack pose contracts failed');console.log('PLAY_FOOD_POSE PASS');
