import assert from 'node:assert/strict';
import { PlayGameState, FOODS, EAT_SECONDS } from '../scene-authoring/yuyuan-area/web/play/state.js';
import { createFoodRegistry } from '../scene-authoring/yuyuan-area/web/play/catalog.js';
import { readFile } from 'node:fs/promises';
const s = new PlayGameState();
s.take('congyoubing'); s.placeVehicle([10, 0, 11], .5);
const vehicle = structuredClone(s.vehicle);
assert.equal(typeof s.applyCollection, 'function');
const incoming = { discovered: ['xiaolongbao'], tasted: ['xiaolongbao'], milestones: [], orphanedProgress: { discovered: [], tasted: [] }, feet: [999,999,999], vehicle: { riding: true } };
assert.ok(s.applyCollection(incoming).ok);
assert.deepEqual(s.vehicle, vehicle);
assert.equal(s.heldItem, 'congyoubing');
assert.ok(s.tasted.has('xiaolongbao') && s.discovered.has('congyoubing'));
assert.ok(s.applyCollection(incoming).ok);
assert.equal(s.tasted.size, 1);
assert.equal(s.applyCollection({ ...incoming, tasted: [null] }).ok, false);
assert.equal(s.tasted.size, 1);
const six = new PlayGameState({ foods: [...FOODS, ...['roujiamo','tanghulu','shuangpinai'].map(id => ({id,labelZh:id}))] });
for (const food of six.foods) { six.take(food.id); six.startEat(); six.eatTick(EAT_SECONDS); }
assert.ok(six.milestones.has('tastes-6'));
six.reset(); assert.ok(six.milestones.has('tastes-6'));
six.resetCollection(); assert.equal(six.milestones.size, 0);
const json = name => readFile(new URL(`../scene-authoring/yuyuan-area/inputs/${name}.json`,import.meta.url),'utf8').then(JSON.parse);
const [catalog,assets,vendors,profiles] = await Promise.all(['food-catalog','play-foods','play-vendors','food-pose-profiles'].map(json));
const registry = createFoodRegistry({catalog,assets,vendors,profiles});
const tracked = new PlayGameState(); tracked.configureCatalog(registry);
tracked.applyCollection(incoming);
const vendorId = registry.vendorsFor('xiaolongbao')[0].vendorId;
assert.ok(tracked.track('xiaolongbao',vendorId));
assert.equal(tracked.navigationGoal().id,'xiaolongbao','explicit revisits must survive already-tasted state');
assert.equal(tracked.toSave().trackedFoodId,'xiaolongbao');
tracked.selectGoal(1); assert.equal(tracked.navigationGoal().id,'congyoubing');
console.log('PLAY_COLLECTION_STATE PASS');
