import assert from'node:assert/strict';import fs from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';import*as T from'three';import{PlayAvatar}from'../scene-authoring/yuyuan-area/web/play/avatar.js';
const A=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../scene-authoring/yuyuan-area');globalThis.self=globalThis;globalThis.createImageBitmap=async()=>({width:4,height:4,close(){}});const{GLTFLoader}=await import(A+'/node_modules/three/examples/jsm/loaders/GLTFLoader.js'),bytes=await fs.readFile(A+'/resources/characters/gray-cat/character.glb'),g=await new Promise((ok,no)=>new GLTFLoader().parse(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'',ok,no));
const avatar=new PlayAvatar({gltfScene:g.scene,animations:g.animations}),body=g.scene.getObjectByName('cat_body'),original=body.geometry;
avatar.setHoldingPose(true);const oldI=body.geometry.attributes.skinIndex.clone(),oldW=body.geometry.attributes.skinWeight.clone();
const cup=new T.Group();cup.userData={sharedPlayFood:true,playTwoHanded:true,playFoodId:'xiaolongbao',cupRearOffset:new T.Vector3(),cupYaw:0};g.scene.add(cup);avatar.setEatingPose(true,.8);for(let i=0;i<3;i++)avatar.update({feet:[0,0,0],yaw:-Math.PI,moving:false,paused:false,dt:1/60});avatar.root.updateMatrixWorld(true);body.skeleton.update();
const smooth=body.geometry,baseline=smooth.clone();baseline.setAttribute('skinIndex',oldI);baseline.setAttribute('skinWeight',oldW);
function strain(geo){body.geometry=geo;const idx=geo.index,pos=geo.attributes.position,a=new T.Vector3(),b=new T.Vector3(),pa=new T.Vector3(),pb=new T.Vector3(),seen=new Set();let count=0,max=0;for(let k=0;k<(idx?.count??pos.count);k+=3){const tri=[0,1,2].map(j=>idx?idx.getX(k+j):k+j);for(let j=0;j<3;j++){const i=tri[j],l=tri[(j+1)%3],key=[Math.min(i,l),Math.max(i,l)].join(':');if(seen.has(key))continue;seen.add(key);a.fromBufferAttribute(pos,i);b.fromBufferAttribute(pos,l);if(Math.max(a.y,b.y)>.46||Math.min(a.y,b.y)<.07)continue;const rest=a.distanceTo(b);body.getVertexPosition(i,pa);body.getVertexPosition(l,pb);const length=pa.distanceTo(pb);if(rest>.002&&length>rest*3&&length>.04){count++;max=Math.max(max,length);}}}return{count,max};}
const before=strain(baseline),after=strain(smooth);assert.ok(after.count<before.count*.5,'less than half the severe underarm edges remain');assert.ok(after.max<before.max*.5,'worst stretched edge reduced by at least half');
const p=smooth.attributes.position,w=smooth.attributes.skinWeight,si=smooth.attributes.skinIndex;for(let i=0;i<p.count;i++){let sum=0;for(let k=0;k<4;k++){sum+=w.getComponent(i,k);if(p.getY(i)>.51||p.getZ(i)<-.13){assert.equal(w.getComponent(i,k),oldW.getComponent(i,k));assert.equal(si.getComponent(i,k),oldI.getComponent(i,k));}}assert.ok(Math.abs(sum-1)<1e-5);}
baseline.dispose();avatar.setEatingPose(false);avatar.setHoldingPose(false);assert.equal(body.geometry,original);avatar.dispose();console.log('PASS real plush skin: strain reduced, face/tail preserved, normalized weights and ownership',JSON.stringify({before,after}));
