// Only new runtime-addition seam and descriptor binding; retained mini fixtures.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{spawnSync}from'node:child_process';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';
import{deriveRuntimeClosure}from'../tools/portable/closure.mjs';import{checkCandidateBinding}from'../tools/portable/candidate_walk_smoke.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');if(!process.env.ART_DIR)throw Error('ART_DIR required outside source');const art=path.resolve(process.env.ART_DIR),base=fs.mkdtempSync(path.join(art,'delivery-mini-')),repo=path.join(base,'repo'),out=path.join(repo,'out-mini');const sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');const put=(rel,text)=>{const p=path.join(repo,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,text,'utf8')};
const area='scene-authoring/yuyuan-area';put(area+'/web/index.html','<!doctype html><script type="importmap">{"imports":{"three":"/node_modules/three/build/three.module.js","@dimforge/rapier3d-compat":"/vendor/@dimforge/rapier3d-compat/rapier.mjs"}}</script>');put(area+'/web/main.js',"fetch('/out/zones-manifest.json');fetch('/out/layout.json'); import '/vendor-src/player/WalkController.js';");put(area+'/scripts/server.mjs',fs.readFileSync(path.join(root,area,'scripts/server.mjs'),'utf8'));put(area+'/node_modules/three/build/three.module.js','export {}');put('node_modules/@dimforge/rapier3d-compat/rapier.mjs','export {}');put('src/player/WalkController.js','export class WalkController {}');
for(const prefix of['',area+'/']){put(prefix+'package.json',JSON.stringify({name:'retained-mini',type:'module'}));put(prefix+'package-lock.json',JSON.stringify({name:'retained-mini',lockfileVersion:3,packages:{'':{name:'retained-mini'}}}))}put('PROJECT.json','{}');put('docs/THIRD-PARTY-NOTICES.md','# synthetic notice');
put('out-mini/zones-manifest.json',JSON.stringify({schema:2,zones:[{id:'garden',file:'zone-garden.glb'}]}));for(const[f,t]of Object.entries({'zone-garden.glb':'glTF retained mini payload','collision-garden.json':'{"colliders":[]}','collision-fangbang.json':'{"colliders":[]}','layout.json':'{}','candidate-version.json':'{"fixture":true}','fangbang-route.json':'{"fixture":true}','control-shots.json':'{"fixture":true}'}))put('out-mini/'+f,t);
const additional=JSON.parse(fs.readFileSync(path.join(root,'tools/portable/world-v1-runtime-paths.json'))),extra=path.join(base,'runtime-paths.json');fs.writeFileSync(extra,JSON.stringify(additional));const whitelist=[{path:area+'/web/',why:'mini viewer'},{path:area+'/scripts/server.mjs',why:'same server'},{path:area+'/package.json',why:'mini deps'},{path:area+'/package-lock.json',why:'mini lock'},{path:area+'/node_modules/',why:'mini stub only'},{path:'node_modules/',why:'mini stub only'},{path:'src/',why:'mini source'},{path:'package.json',why:'mini root deps'},{path:'package-lock.json',why:'mini root lock'},{path:'PROJECT.json',why:'mini scope'},{path:'docs/THIRD-PARTY-NOTICES.md',why:'mini notice'}];const source=path.join(base,'source-paths.json');fs.writeFileSync(source,JSON.stringify(whitelist));
const env={...process.env,GIT_AUTHOR_NAME:'fixture',GIT_AUTHOR_EMAIL:'fixture@pawborough.local',GIT_COMMITTER_NAME:'fixture',GIT_COMMITTER_EMAIL:'fixture@pawborough.local'};for(const args of[['init','-q',repo],['-C',repo,'add','-A'],['-C',repo,'commit','-q','-m','retained delivery mini']]){const r=spawnSync('git',args,{env,encoding:'utf8'});assert.equal(r.status,0,r.stderr)}const head=spawnSync('git',['-C',repo,'rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim();const run=(name,tool,args)=>{const r=spawnSync(process.execPath,[path.join(root,tool),...args],{encoding:'utf8'});fs.writeFileSync(path.join(base,name+'.log'),r.stdout+r.stderr);return r.status};let passed=0;
const c=await deriveRuntimeClosure({outDir:out,zonesManifestPath:path.join(out,'zones-manifest.json'),webDir:path.join(repo,area,'web'),runtimePaths:additional});assert.equal(c.missing.length,0);for(const e of additional){const f=c.files.find(f=>f.path===e.path);assert.ok(f&&f.rules.some(r=>r.startsWith('R7:')));assert.equal(f.sha256,sha(path.join(out,e.path)))}assert.ok(c.files.some(f=>f.path==='zone-garden.glb'));passed++;
const pkg=path.join(base,'package');const common=['--repo',repo,'--head',head,'--out-dir',out,'--manifest',path.join(out,'zones-manifest.json'),'--source-paths',source];assert.equal(run('pack','tools/portable/pack.mjs',[...common,'--out',pkg,'--runtime-paths',extra]),0);assert.equal(run('verify','tools/portable/verify.mjs',['--package',pkg,'--report',path.join(base,'verify.json')]),0);const dest=path.join(base,'restored');assert.equal(run('restore','tools/portable/restore.mjs',['--package',pkg,'--dest',dest,'--port','5606','--skip-install','--no-browser','--check-and-exit','--evidence-dir',path.join(base,'restore-evidence')]),0);for(const e of additional)assert.equal(sha(path.join(dest,area,'out-mini',e.path)),sha(path.join(out,e.path)));passed++;
for(const[name,paths]of[['missing-extra',[{path:'absent.json',why:'must fail'}]],['escape-extra',[{path:'../outside.json',why:'must fail'}]]]){const file=path.join(base,name+'.json');fs.writeFileSync(file,JSON.stringify(paths));assert.notEqual(run(name,'tools/portable/pack.mjs',[...common,'--out',path.join(base,name+'-package'),'--runtime-paths',file]),0);passed++}
const bytes=fs.readFileSync(path.join(out,'zones-manifest.json')),version={schemaVersion:1,projectId:'pawborough-world',candidateId:'unit-binding',sourceBuildHead:'a'.repeat(40),packageHead:'b'.repeat(40),manifestSha256:createHash('sha256').update(bytes).digest('hex'),technicalStatus:'unverified'};assert.equal(checkCandidateBinding(version,bytes,version.packageHead),true);assert.throws(()=>checkCandidateBinding({...version,fixture:true},bytes,version.packageHead));assert.throws(()=>checkCandidateBinding({...version,manifestSha256:'0'.repeat(64)},bytes,version.packageHead));assert.throws(()=>checkCandidateBinding(version,bytes,'c'.repeat(40)));passed++;
const config=JSON.parse(fs.readFileSync(path.join(root,'tools/portable/world-v1-source-paths.json')));for(const e of config)assert.ok(fs.existsSync(path.join(root,e.path)),e.path);assert.ok(!config.some(e=>/artifacts|\.jsonl|\.glb/.test(e.path)));passed++;
fs.appendFileSync(path.join(art,'delivery-fixtures-record.jsonl'),JSON.stringify({path:base,retainedAt:new Date().toISOString(),purpose:'new delivery seam only; no real world rebuild/walk'})+'\n');fs.writeFileSync(path.join(art,'DELIVERY-WIRING-CHECK.json'),JSON.stringify({time:new Date().toISOString(),pass:true,passedGroups:passed,fixture:true,retainedDir:base,checks:['additive runtime rules/hash','mini pack-verify-restore extra files','missing extra nonzero','path escape nonzero','candidate binding validators','current source configuration paths']},null,2)+'\n');console.log('delivery wiring PASS',passed,'retained',base);
