// H2 (adoption batch 20260919): regenerate ONE dataset's review-manifest.cm.json
// from its CURRENT review-manifest.json. tools/build_compressed_dist.mjs
// compresses every world/** GLB in one pass and is the tool that produced the
// committed *.cm.glb assets — but a dataset whose original manifest moved on
// (fangbang-temple-v4 gained the tree, east shops, props across later batches)
// ends up with a STALE cm manifest that would fail the page's integrity
// checks under the now-default compressed state. This tool re-derives the
// cm manifest in place: every .glb field with an existing *.cm.glb sibling is
// repointed to it with the true bytes/sha256; anything without a compressed
// sibling stays original (honest fallback, one 404 round-trip per page load).
// No GLB is compressed or written here — world/ bytes are never touched.
//
// Run: node tools/make_cm_manifest.mjs --dataset fangbang-temple-v4
import { createHash } from 'node:crypto';
import { readFile, writeFile, access } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sha = (b) => createHash('sha256').update(b).digest('hex');

const argIdx = process.argv.indexOf('--dataset');
const dataset = argIdx > -1 ? process.argv[argIdx + 1] : null;
if (!dataset) { console.error('usage: node tools/make_cm_manifest.mjs --dataset <id>'); process.exit(1); }

const srcPath = resolve(root, `world/${dataset}/review-manifest.json`);
const outPath = resolve(root, `world/${dataset}/review-manifest.cm.json`);
const tree = JSON.parse(await readFile(srcPath, 'utf8'));

// collect paths first, then rewrite (two passes so repoint decisions are uniform)
function collectPaths(node, out = []) {
  if (Array.isArray(node)) { for (const x of node) collectPaths(x, out); return out; }
  if (node && typeof node === 'object') {
    for (const [k, v] of Object.entries(node)) {
      if (typeof v === 'string' && v.endsWith('.glb') && !v.endsWith('.cm.glb')) out.push({ node, key: k, value: v });
      else collectPaths(v, out);
    }
  }
  return out;
}
const glbFields = collectPaths(tree);
let repointed = 0, kept = 0;
for (const { node, key, value } of glbFields) {
  const cmCandidate = value.replace(/\.glb$/, '.cm.glb');
  const cmAbs = resolve(root, cmCandidate);
  try {
    const b = await readFile(cmAbs);
    node[key] = './' + cmCandidate.replace(/^\.\//, '');
    if ('bytes' in node) node.bytes = b.byteLength;
    if ('sha256' in node) node.sha256 = sha(b);
    repointed += 1;
  } catch {
    kept += 1; // no compressed sibling — stays original
  }
}

// gltfpack -kn expands shared texture objects (one per primitive) — mirror the
// WorldLoader image-sharing-ceiling adjustment build_compressed_dist.mjs makes
if (tree.sceneImages?.count) {
  tree.sceneImages = {
    ...tree.sceneImages,
    count: tree.sceneImages.count * 2,
    note: 'doubled for the compressed variant: gltfpack -kn expands shared texture objects (one per primitive)',
  };
}
tree.compressedVariant = {
  note: 'regenerated by tools/make_cm_manifest.mjs from the current review-manifest.json: every .glb field with an on-disk .cm.glb sibling repointed with true bytes/sha256; others stay original',
  gltfpack: 'meshopt + KHR_mesh_quantization (-cc -kn); textures untouched',
};
await writeFile(outPath, JSON.stringify(tree, null, 2) + '\n');
console.log(`CM_MANIFEST_READY world/${dataset}/review-manifest.cm.json repointed=${repointed} keptOriginal=${kept}`);
