import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const app=document.querySelector('#app'),stats=document.querySelector('#stats'),viewsEl=document.querySelector('#views');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.AgXToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.info.autoReset=false;app.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','方浜中路完整三维街景');
const scene=new T.Scene();scene.background=new T.Color(0xdde3df);scene.fog=new T.Fog(0xdde3df,180,380);
const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=.28;room.dispose();pmrem.dispose();
scene.add(new T.HemisphereLight(0xe8f0f5,0xb9b2a1,.72));
const sun=new T.DirectionalLight(0xfff5ea,2.4);sun.position.set(-20,65,48);sun.target.position.set(42,0,4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-75,right:75,top:60,bottom:-60,near:.5,far:230});sun.shadow.camera.updateProjectionMatrix();sun.shadow.normalBias=.025;sun.shadow.bias=-.0002;sun.shadow.autoUpdate=false;scene.add(sun,sun.target);
const outside=new T.Mesh(new T.PlaneGeometry(600,600),new T.MeshStandardMaterial({color:0xbabdb4,roughness:.98}));outside.rotation.x=-Math.PI/2;outside.position.set(42,-.18,4);outside.receiveShadow=true;scene.add(outside);
const camera=new T.PerspectiveCamera(45,1,.1,600),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minDistance=.5;controls.maxDistance=220;controls.maxPolarAngle=Math.PI;
const world=new T.Group();world.name='complete-fangbang-world';scene.add(world);
const clay=new T.MeshStandardMaterial({color:0xb8b7ae,roughness:.86});
const labels={'full-west':'全段·西','full-east':'全段·东','eye-west':'沿街·西向东','eye-east':'沿街·东向西',across:'对街北望',corner:'光启路口',lane:'支弄B',catwall:'猫墙',plaza:'玄扈台前空地','corner-close':'路名牌近景','module-near':'店面近景'};
let streetKitNodeCount=0;let ready=false,clayOn=false,selected='full-west',cameras=[],instances=null,manifest=null,lastRender={},loadStats={},fetchRows=[];
function resources(){const g=new Set(),m=new Set(),t=new Set();let triangles=0,meshes=0;world.traverse(o=>{if(!o.isMesh)return;meshes++;g.add(o.geometry);triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;for(const mat of [o.material].flat()){m.add(mat);for(const v of Object.values(mat))if(v?.isTexture)t.add(v);}});return{meshes,triangles,uniqueGeometries:g.size,uniqueMaterials:m.size,uniqueTextures:t.size};}
function record(){return{ready,view:selected,mode:clayOn?'clay':'pbr',resources:resources(),expectedWorldTriangles:manifest?.placedTriangles,streetKitLoaded:streetKitNodeCount>0,streetKitNodeCount,loadMode:'single_assembly_sharing_embedded_images',placedBuildingCount:instances?.instances.length,assets:manifest,load:loadStats,fetches:fetchRows,render:lastRender,camera:{position:camera.position.toArray(),target:controls.target.toArray(),fov:camera.fov,near:camera.near},framebuffer:renderer.getSize(new T.Vector2()).toArray(),lighting:{shadows:renderer.shadowMap.enabled,shadowBias:sun.shadow.bias,shadowNormalBias:sun.shadow.normalBias,toneMapping:'AgX',exposure:1,environmentIntensity:.28,hemisphereIntensity:.72,sunIntensity:2.4,sunPosition:sun.position.toArray()},browserRendered:true,walkingVerified:false,gameIntegrated:false,ownerAdopted:false};}
function render(){if(!ready)return;const near=Math.max(.05,Math.min(2,camera.position.distanceTo(controls.target)*.003));if(camera.near!==near){camera.near=near;camera.updateProjectionMatrix();}renderer.info.reset();const started=performance.now();renderer.render(scene,camera);lastRender={callsIncludingShadow:renderer.info.render.calls,trianglesIncludingShadow:renderer.info.render.triangles,cpuSubmitMs:performance.now()-started};const r=resources();stats.textContent=`${instances.instances.length} 门面＋完整路面/支弄/前庭 · ${r.triangles.toLocaleString()} 三角形\n几何/材质/纹理 ${r.uniqueGeometries}/${r.uniqueMaterials}/${r.uniqueTextures} · 本机资产 ${(loadStats.bytes/1e6).toFixed(2)} MB\n拖动旋转 · 滚轮缩放 · 右键平移`;document.querySelector('#record').textContent=JSON.stringify(record(),null,2);}
function setView(id){const v=cameras.find(c=>c.id===id);if(!v)return;selected=id;camera.position.set(...v.positionGlb);controls.target.set(...v.targetGlb);camera.fov=2*Math.atan(v.sensorWidthMm/2/v.lensMm/camera.aspect)*180/Math.PI;camera.updateProjectionMatrix();controls.update();for(const b of viewsEl.querySelectorAll('[data-view]'))b.classList.toggle('on',b.dataset.view===id);render();}
function setupButtons(){for(const c of cameras){const b=document.createElement('button');b.textContent=labels[c.id]??c.id;b.dataset.view=c.id;b.onclick=()=>setView(c.id);viewsEl.appendChild(b);}const c=document.createElement('button');c.textContent='灰模';c.onclick=()=>{clayOn=!clayOn;scene.overrideMaterial=clayOn?clay:null;c.classList.toggle('on',clayOn);sun.shadow.needsUpdate=true;render();};viewsEl.appendChild(c);const save=document.createElement('button');save.textContent='保存实测图';save.onclick=async()=>{if(!ready)return;render();const image=renderer.domElement.toDataURL('image/jpeg',.94);try{const res=await fetch('/__review-evidence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:`${selected}-${clayOn?'clay':'pbr'}`,image,record:record()})});if(!res.ok)throw Error(`保存 HTTP ${res.status}`);document.querySelector('#notice').textContent='当前WebGL画面与数据已保存。';}catch(e){document.querySelector('#notice').textContent=e.message;}};viewsEl.appendChild(save);}
async function json(path){const r=await fetch(path);if(!r.ok)throw Error(`${path} HTTP ${r.status}`);return r.json();}
async function glb(path){const t0=performance.now(),r=await fetch(path,{cache:'no-cache'});if(!r.ok)throw Error(`${path} HTTP ${r.status}`);const data=await r.arrayBuffer(),t1=performance.now();const model=await new GLTFLoader().parseAsync(data,new URL('.',new URL(path,location.href)).href),t2=performance.now();fetchRows.push({path,bytes:data.byteLength,fetchMs:t1-t0,parseImagesReadyMs:t2-t1});stats.textContent=`已读入 ${fetchRows.length}/1 个资产…`;return model.scene;}
async function load(){const t0=performance.now();[instances,manifest,{cameras}]=await Promise.all([json('./world/instances.json'),json('./world/review-manifest.json'),json('./world/cameras.json')]);setupButtons();setView('full-west');const assembled=await glb(manifest.worldAssembly.path);assembled.name='reviewed-world';world.add(assembled);assembled.traverse(o=>{if(o.name.startsWith('street-kit__'))streetKitNodeCount++;});world.traverse(o=>{if(o.isMesh){o.castShadow=![o.material].flat().every(m=>/asphalt|paving/i.test(m.name));o.receiveShadow=true;for(const m of [o.material].flat())for(const v of Object.values(m))if(v?.isTexture)v.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());}});world.updateMatrixWorld(true);const total=resources().triangles;if(total!==manifest.placedTriangles)throw Error(`几何不完整：实际 ${total} / 预期 ${manifest.placedTriangles}`);const parsed=performance.now();await renderer.compileAsync(scene,camera);const compiled=performance.now();loadStats={bytes:fetchRows.reduce((s,x)=>s+x.bytes,0),allAssetsReadyMs:parsed-t0,shaderCompileMs:compiled-parsed,localOnly:true,fpsNotMeasured:true};ready=true;sun.shadow.needsUpdate=true;render();document.querySelector('#notice').textContent='完整世界已载入 · 独立场景预览，尚未接入游戏或验证玩家行走';}
controls.addEventListener('change',render);new ResizeObserver(()=>{const w=app.clientWidth,h=app.clientHeight,k=Math.min(1,1600/w,900/h);renderer.setSize(Math.round(w*k),Math.round(h*k),false);camera.aspect=w/h;const v=cameras.find(v=>v.id===selected);if(v)camera.fov=2*Math.atan(v.sensorWidthMm/2/v.lensMm/camera.aspect)*180/Math.PI;camera.updateProjectionMatrix();render();}).observe(app);
void load().catch(e=>{stats.textContent='载入失败：'+e.message;document.querySelector('#notice').textContent='未取得完整场景，不计为验证通过。';console.error(e);});
window.addEventListener('pagehide',()=>{controls.dispose();renderer.dispose();renderer.forceContextLoss();});
